### ISSUE TITLE
Ajax error 500 when file doesn't exist

### ISSUE THREAD

**Issue by kaisermann** [cyberhobo/media-library-svg-display#1]
If, for some reason, a certain `.svg` file (the actual file, not the wordpress media) was wrongly deleted,  the [`simplexml_load_file `](https://github.com/press-bits/media-library-svg-display/blob/master/source/ScalableVectorGraphicsDisplay.php#L86) throws an error and the media library fails to even load any image.

**Comment by cyberhobo** [comment]
Fixed by #2.
